services:
  # Backend API Service
  - type: web
    name: healthynola-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd web-backend && npm install && npm run migrate
    startCommand: cd web-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_1UEBztQxaCX3@ep-silent-sky-adsoykyi-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://healthynola.vercel.app

# Database is hosted on Neon (external)
# No need for Render database since we're using Neon

